# Generated by Django 4.2.7 on 2023-12-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_follow_user_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
