# Generated by Django 4.2.7 on 2023-12-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_like_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_follow',
        ),
    ]
